server: 
  port: 3344 
  
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/livelyRyan/microservicecloud-config.git #GitHub上面的git仓库名字
          # 指定子目录
          searchPaths: microservicecloud-config-server,microservicecloud-config-client
  rabbitmq:
    host: localhost    #公网地址
    port: 15672
    username: guest
    password: guest
          
management: 
  security: # springboot 1.5.X 以上默认开通了安全认证，需要关闭
    enabled: false