server:
  port: 80
spring:
  application:
    name: microservicecloud-consumer-dept-consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 客户端不进行consul服务注册
        register: false 
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: microservicecloud-consumer-dept-consul-80
  build.version: 0.0.1-SNAPSHOT