server:
  port: 8001

spring:
   application:
    name: microservicecloud-dept
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001-zuul
    prefer-ip-address: true     #访问路径可以显示IP地址
      
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: microservicecloud-provider-dept-zuul-8001
  build.version: 0.0.1-SNAPSHOT
      
      
      
 

